spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000
