spring:
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

zonky:
  test:
    database:
      provider: ZONKY
      type: POSTGRES
